# Site settings
title: Coffeechiou
description: Ethan's coffee guides.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "echiou.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: pretty

# collections
collections:
  guides:
    output: true
    permalink: /guides/:path/
